// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_CUSTOMER_LOGIN_SUCCESS = 'AUTH_CUSTOMER_LOGIN_SUCCESS';
export const AUTH_AUTO_RENEW_SUCCESS = 'AUTH_AUTO_RENEW_SUCCESS';
export const AUTH_PHOTO_SUCCESS = 'AUTH_PHOTO_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_DATA_UPDATE_SUCCESS = 'AUTH_DATA_UPDATE_SUCCESS';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const AUTH_ADMIN_LOGIN_SUCCESS = 'AUTH_ADMIN_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';


// Content
export const CONTENT_START = 'CONTENT_START';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_FAIL = 'CONTENT_FAIL';


// Frontend
export const HOME_RESET = 'HOME_RESET';
export const HOME_START = 'HOME_START';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAIL = 'HOME_FAIL';

export const ABOUT_RESET = 'ABOUT_RESET';
export const ABOUT_START = 'ABOUT_START';
export const ABOUT_SUCCESS = 'ABOUT_SUCCESS';
export const ABOUT_FAIL = 'ABOUT_FAIL';

export const GALLERY_RESET = 'GALLERY_RESET';
export const GALLERY_START = 'GALLERY_START';
export const GALLERY_SUCCESS = 'GALLERY_SUCCESS';
export const GALLERY_FAIL = 'GALLERY_FAIL';

export const TRAININGS_RESET = 'TRAININGS_RESET';
export const TRAININGS_START = 'TRAININGS_START';
export const TRAININGS_SUCCESS = 'TRAININGS_SUCCESS';
export const TRAININGS_FAIL = 'TRAININGS_FAIL';

export const PUBLICATIONS_RESET = 'PUBLICATIONS_RESET';
export const PUBLICATIONS_START = 'PUBLICATIONS_START';
export const PUBLICATIONS_SUCCESS = 'PUBLICATIONS_SUCCESS';
export const PUBLICATIONS_FAIL = 'PUBLICATIONS_FAIL';

export const CONTACT_RESET = 'CONTACT_RESET';
export const CONTACT_START = 'CONTACT_START';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAIL = 'CONTACT_FAIL';


// Backend
export const ADMINS_RESET = 'ADMINS_RESET';
export const ADMINS_START = 'ADMINS_START';
export const ADMINS_SUCCESS = 'ADMINS_SUCCESS';
export const ADMINS_FAIL = 'ADMINS_FAIL';

export const CMS_RESET = 'CMS_RESET';
export const CMS_START = 'CMS_START';
export const CMS_SUCCESS = 'CMS_SUCCESS';
export const CMS_FAIL = 'CMS_FAIL';

export const NOTIFICATIONS_RESET = 'NOTIFICATIONS_RESET';
export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL';

export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const FEATURES_RESET = 'FEATURES_RESET';
export const FEATURES_START = 'FEATURES_START';
export const FEATURES_SUCCESS = 'FEATURES_SUCCESS';
export const FEATURES_FAIL = 'FEATURES_FAIL';

export const LANGUAGES_RESET = 'LANGUAGES_RESET';
export const LANGUAGES_START = 'LANGUAGES_START';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAIL = 'LANGUAGES_FAIL';

export const ROLES_RESET = 'ROLES_RESET';
export const ROLES_START = 'ROLES_START';
export const ROLES_SUCCESS = 'ROLES_SUCCESS';
export const ROLES_FAIL = 'ROLES_FAIL';

export const USERS_RESET = 'USERS_RESET';
export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const SETTINGS_RESET = 'SETTINGS_RESET';
export const SETTINGS_START = 'SETTINGS_START';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAIL = 'SETTINGS_FAIL';

export const SUBJECTS_RESET = 'SUBJECTS_RESET';
export const SUBJECTS_START = 'SUBJECTS_START';
export const SUBJECTS_SUCCESS = 'SUBJECTS_SUCCESS';
export const SUBJECTS_FAIL = 'SUBJECTS_FAIL';

export const TESTIMONIES_RESET = 'TESTIMONIES_RESET';
export const TESTIMONIES_START = 'TESTIMONIES_START';
export const TESTIMONIES_SUCCESS = 'TESTIMONIES_SUCCESS';
export const TESTIMONIES_FAIL = 'TESTIMONIES_FAIL';

export const TRAINING_CATEGORIES_RESET = 'TRAINING_CATEGORIES_RESET';
export const TRAINING_CATEGORIES_START = 'TRAINING_CATEGORIES_START';
export const TRAINING_CATEGORIES_SUCCESS = 'TRAINING_CATEGORIES_SUCCESS';
export const TRAINING_CATEGORIES_FAIL = 'TRAINING_CATEGORIES_FAIL';

export const TRAINING_LEVELS_RESET = 'TRAINING_LEVELS_RESET';
export const TRAINING_LEVELS_START = 'TRAINING_LEVELS_START';
export const TRAINING_LEVELS_SUCCESS = 'TRAINING_LEVELS_SUCCESS';
export const TRAINING_LEVELS_FAIL = 'TRAINING_LEVELS_FAIL';

export const PUBLICATION_CATEGORIES_RESET = 'PUBLICATION_CATEGORIES_RESET';
export const PUBLICATION_CATEGORIES_START = 'PUBLICATION_CATEGORIES_START';
export const PUBLICATION_CATEGORIES_SUCCESS = 'PUBLICATION_CATEGORIES_SUCCESS';
export const PUBLICATION_CATEGORIES_FAIL = 'PUBLICATION_CATEGORIES_FAIL';

export const IMAGES_RESET = 'IMAGES_RESET';
export const IMAGES_START = 'IMAGES_START';
export const IMAGES_SUCCESS = 'IMAGES_SUCCESS';
export const IMAGES_FAIL = 'IMAGES_FAIL';
